---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: smartos
  driver_config:
    box: livinginthepast/smartos-base64
    vagrantfile_erb: test/templates/Vagrantfile.smartos.erb
    zone:
      platform_image: 'latest'
      name: base64
      brand: joyent
      image: 5c7d0d24-3475-11e5-8e67-27953a8b237e
  provisioner:
    name: chef_zero
    nodes_path: test/nodes
    environments_path: test/environments
    sudo: true
    chef_omnibus_url: https://raw.github.com/wanelo-chef/chef-bootstrap/master/latest.sh
    client_rb:
        environment: my-environment

suites:
  - name: master
    run_list:
      - recipe[test-setup::java]
      - recipe[solr::master]
  - name: replica
    attributes:
      solr:
        replica:
          solr_master: roles:solr-master
          master_ip_attribute: privateaddress
    run_list:
      - recipe[test-setup::java]
      - recipe[solr::replica]
  - name: solr3
    attributes:
      solr:
        version: 3.6.2
        source_url: https://us-east.manta.joyent.com/wanelo/public/cache/solr/apache-solr-3.6.2.tgz
    run_list:
      - recipe[test-setup::java]
      - recipe[solr::master]
  - name: provider-default
    run_list:
      - recipe[test-setup::default_provider]
